"""add country_dialing_code to registrations

Revision ID: 417ed39381f4
Revises: 51e15619c891
Create Date: 2026-02-22 15:02:50.140369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417ed39381f4'
down_revision: Union[str, Sequence[str], None] = '51e15619c891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('country_dialing_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'country_dialing_code')
    # ### end Alembic commands ###
